### ISSUE TITLE
Under-construction website 

### ISSUE THREAD

**Issue by PaulMuigai** [IgwaXP/Igwa-Website-Construction#13]
Please change "Your journey to live fully, explore endlessly, one experience at a time" 
to 
"Book all leisure activities on one platform. Coming soon." 

Then where the bold statement in white that reads "we are currently working ..." 
is where the above Igwa description should be. 

The feinted out grey text can be the "We are currently working on a new super awesome website"

**Comment by Duncan-Kiragu** [comment]
> change to 

> Book all experiences on one platform. Coming soon

>  I told a few people about leisure and they would ask me what that is

@PaulMuigai
